sudo: required
cache: bundler
dist: trusty
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
gemfiles:
  - gemfiles/standalone.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
script: "bundle exec rspec && bundle exec codeclimate-test-reporter"
before_install:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get update -q
  - sudo apt-get install libsodium-dev -y
  - gem install bundler
